MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://VGGImageNetPretrained/JCJOHNS/VGG-16" 
  BACKBONE:
    CONV_BODY: "VGG16-OICR"
  WSOD_ON: True
  FASTER_RCNN: False
  ROI_HEADS:
    SCORE_THRESH: 0.0
    NMS: 0.3
  ROI_BOX_HEAD:
    POOLER_METHOD: "ROIPool"
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.125,)
    FEATURE_EXTRACTOR: "VGG16.roi_head"
  ROI_WEAK_HEAD:
    PREDICTOR: "MISTPredictor"
    LOSS: "RoIRegLoss"
    OICR_P: 0.15
    REGRESS_ON: True
DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_val",)
PROPOSAL_FILES:
  TRAIN: ('proposal/MCG-coco_2014_train-boxes.pkl',)
  TEST:  ('proposal/MCG-coco_2014_val-boxes.pkl',)
DATALOADER:
  SIZE_DIVISIBILITY: 32
INPUT:
  MIN_SIZE_TRAIN: (480, 576, 688, 864, 1000, 1200) 
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 2000
SOLVER:
  IMS_PER_BATCH: 8 
  BASE_LR: 0.01 
  WEIGHT_DECAY: 0.0001
  STEPS: (90000, 120000)
  MAX_ITER: 130000
  CHECKPOINT_PERIOD: 10000
TEST:
  BBOX_AUG:
    ENABLED: True
    HEUR: "AVG"
    H_FLIP: True
    SCALES: (480, 576, 688, 864, 1000, 1200) 
    MAX_SIZE: 2000
    SCALE_H_FLIP: True