MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://VGGImageNetPretrained/JCJOHNS/VGG-16" 
  BACKBONE:
    CONV_BODY: "VGG16-OICR"
  WSOD_ON: True
  FASTER_RCNN: False
  ROI_HEADS:
    SCORE_THRESH: 0.0
    NMS: 0.3
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
    POOLER_METHOD: "ROIPool"
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.125,)
    FEATURE_EXTRACTOR: "VGG16.roi_head"
  ROI_WEAK_HEAD:
    PREDICTOR: "MISTPredictor"
    LOSS: "RoIRegLoss"
    OICR_P: 0.15
    REGRESS_ON: True
DB:
  METHOD: 'concrete'
DATASETS:
  TRAIN: ("voc_2012_train", "voc_2012_val")
  TEST: ("voc_2007_test",)
PROPOSAL_FILES:
  TRAIN: ('proposal/SS-voc_2012_train-boxes.pkl','proposal/SS-voc_2012_val-boxes.pkl')
  TEST:  ('proposal/SS-voc_2007_test-boxes.pkl',)
DATALOADER:
  SIZE_DIVISIBILITY: 32
INPUT:
  MIN_SIZE_TRAIN: (480, 576, 688, 864, 1000, 1200) 
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 2000
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  WARMUP_ITERS: 200
  STEPS: (20000, 26700)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 1000
SOLVER_CDB:
  BASE_LR: 0.0001
  GAMMA: 3.0
  WEIGHT_DECAY: 0.0001
  STEPS: (20000, 26700)
TEST:
  BBOX_AUG:
    ENABLED: True
    HEUR: "AVG"
    H_FLIP: True
    SCALES: (480, 576, 688, 864, 1000, 1200) 
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
SEED: 1234